require:
  - rubocop-performance
  - rubocop-rspec

AllCops:
  NewCops: enable
  UseCache: false
  TargetRubyVersion: 2.5
  DisplayCopNames: true
  Exclude:
    - 'Rakefile'
    - 'spec/spec_helper.rb'
    - 'spec/factories/*.rb'
    - 'vendor/**/*'

Style/Documentation:
  Enabled: false

Layout/LineLength:
  Max: 120

Metrics/ClassLength:
  Max: 150

Metrics/BlockLength:
  Enabled: false

Metrics/MethodLength:
  Max: 15

Style/RegexpLiteral:
  Enabled: false

Layout/FirstArrayElementIndentation:
  Enabled: false

Layout/FirstHashElementIndentation:
  Enabled: false

Lint/AmbiguousBlockAssociation:
  Exclude:
    - 'spec/**/*.rb'
